### ISSUE TITLE
[ERROR] Cannot find module. 

### ISSUE THREAD

**Issue by n0w33d** [reisxd/TizenTube#104] opened 2024-11-21 00:53 UTC
Upon launching this module the following error is displayed

> ! Error: Could not find the module @foxreis/tizentube

No further messages appear to allow for troubleshooting. 

Please let me know what other info you need to help resolve. 

Tangent:  is there a way for me to fork your repo and host the TizenTube module for myself?

**Comment by KawaKode** [comment] 2024-11-21 18:42
Hello, same thing here on TizenBrew 1.4.3

**Comment by kelvinkad** [comment] 2024-11-25 21:39
Same thing here

**Comment by kelvinkad** [comment] 2024-11-27 20:58
@reisxd why this os happening? Any idea?

**Comment by kelvinkad** [comment] 2024-11-29 14:05
Any news about this?

**Comment by kelvinkad** [comment] 2024-12-10 14:31
@reisxd

**Comment by Nghia323223** [comment] 2024-12-14 13:06
So am I, happened on Tizen 1.4.2/.3.

**Comment by reisxd** [comment] 2024-12-25 20:57
Duplicate of https://github.com/reisxd/TizenBrew/issues/75. Also not related to TizenTube.

**Closed by reisxd** 2024-12-25 20:57 UTC
