### ISSUE TITLE
[BUG] SponsorBlock detect a skipping session on the last/first part of a video, but decided to spam about it instead of playing/ending a video

### ISSUE THREAD

**Issue by Crystal4704** [reisxd/TizenTube#85] opened 2024-09-01 06:05 UTC
Model : UA43TU8500KXXV / Tizen 5.5

Software version : T-NKLUABC-2503.0 , BT - S

Status code : 20401_AE2_IL233

Sub-micom version : T-NLINTV-1005

Steps to reproduce :
Open TizenTube (with default config)
Choose a video that had 1-2s segments at the start (or end) of a video

Quick note : It sometimes happen (some videos are affected, others aren't)

What should happen : 

The video would play and end the video normally (based on what SponsorBlock shown)

What actually happen :

- If SponsorBlock detected on first segments : It decided to spam about it, detected as a segment multiple times but not actually skipping (and the app could ended up crashed after it)

- If SponsorBlock detected on last segments : It detected as a segment, skipping it but it won't end the video. Causing it to loop back to the beginning (but the app won't crash this time)

Video included :
https://github.com/user-attachments/assets/c13c6c90-82c1-4da5-8b4e-9e6c9a2f424c
https://github.com/user-attachments/assets/7268ee25-3f3c-4ad8-bfc6-2a2d8ebd33f7

**Comment by reisxd** [comment] 2024-09-01 09:57
Dupe of #27

**Closed by reisxd** 2024-09-01 09:57 UTC
