### ISSUE TITLE
Feature to automatically dismiss the "Video paused. Continue watching?"

### ISSUE THREAD

**Issue by IntelCorei5-8350u** [reisxd/TizenTube#50] opened 2024-04-23 15:55 UTC
![DSC_0170](https://github.com/reisxd/TizenTube/assets/105188534/2e5c9256-fbd5-403c-be6f-f97bdfc7a4a7)

Appreciate it if it was added. Sometimes people including myself just want their TV to continuous play their favorite playlist in background for hours, without touching the remote.

**Comment by reisxd** [comment] 2024-04-24 07:54
Dupe of #45

**Closed by reisxd** 2024-04-24 07:54 UTC
