### ISSUE TITLE
Play/Pause/Skip buttons nonfunctioning

### ISSUE THREAD

**Issue by htnrdy** [reisxd/TizenTube#53] opened 2024-04-25 17:57 UTC
There is a small issue with the bottom row keys (play, pause, skip forward, skip backward) not functioning on my remote.  I tested the default YouTube app and it works as expected.

- Remote: BN59-01315A 
- TV: UN50RU7100FXZA

I noticed commit 31d6a1c adds support for `MediaPlayPause` keys, will this fix the issue? Also, how do I use the version `1.2.7` referenced in the commit? Will we have to wait for a new release?

Thanks for all the work you do, much appreciated.

**Comment by davidngedu** [comment] 2024-05-03 06:03
Same here.

**Comment by kascuan** [comment] 2024-06-17 22:53
I also have this issue, I think the issue is the control we are using has separate buttons for Play and Pause.  The SmartThings Android app shows a control with a play/pause single button which does exactly what is expected.  I believe this may be a case of registering the MediaPlay and MediaPause buttons too.

**Comment by T-ADevelopment** [comment] 2024-07-24 21:00
I have created an fix for TizenTube to get the Play, Pause, Skip buttons working you can install it by clicking the Green button when in the Modules loader then Add NPM Module and typing @tadevelopment/tizentubefix 
Hope this helps someone :)

**Comment by reisxd** [comment] 2024-07-29 10:39
Fixed with commit 637f52004ae9109bec1c986070d3477e1787b6a7.

**Closed by reisxd** 2024-07-29 10:39 UTC
